### ISSUE TITLE
Differentiating b/w .py and no extension

### ISSUE THREAD

**Issue by sisaha9** [DavidFernandezChaves/detectron2_ros#4]
Currently when the repo is cloned detectron2_ros in src does not have the .py extension. Since I was planning on adding one more .py file I decided to rename detectron2_ros to detectron2_ros.py and edit the launch file to reflect that. It started giving can't find detectron2_ros.msg does not exist. Am I missing some other step?

**Comment by DavidFernandezChaves** [comment]
I don't have a clear answer to why the .py doesn't accept it as a package. In other projects I have not had these problems so I understand that it is because of the difference between Python versions. In any case, to make use of the CNN you can create another independent package where you can insert your code.

**Comment by sisaha9** [comment]
Thanks!
